In [1]:
import covers

In [ ]:
covertable = covers.get_covers_table("../data/main_dataset.csv")

In [ ]:
covertable

In [ ]:
covertable.columns

In [ ]:
covertable['img_paths']

In [ ]:
categorylist = list(set(list(covertable['category'])))

In [ ]:
categorylist

In [ ]:
categoryvals = list(range(len(categorylist)))

In [ ]:
categoryvals

In [ ]:
cat2label = dict(zip(categorylist, categoryvals))

In [ ]:
covertable['label'] = [cat2label[x] for x in covertable['category']]

In [ ]:
covertable['label']

In [ ]:
cat2label

In [ ]:
covertable['category'][-10:]

In [ ]:
covertable.iloc[560]['img_paths']

In [ ]:
coversdataset = covers.CoversDataset("../data/main_dataset.csv", "../data/", (300,200))

In [ ]:
testrow = coversdataset[5]

In [ ]:
testrow

In [ ]:
coversdataset.cat2label

In [ ]:
from torchvision.transforms import ToPILImage

In [ ]:
pilimagizer = ToPILImage()

In [ ]:
from matplotlib.pyplot import show

In [ ]:
show(pilimagizer(testrow[0]))

In [ ]:
pilimagizer(testrow[0])

In [ ]:
testrow[0]

In [ ]:
import torch

In [ ]:
randomvec = torch.randn(32)

In [ ]:
randomvec

In [ ]:
import torch.nn

In [ ]:
rand2 = torch.softmax(randomvec, 0)

In [ ]:
rand2

In [ ]:
sum(rand2)

In [ ]:
rand3 = torch.log_softmax(randomvec, 0)

In [ ]:
rand3

In [ ]:
sum(rand3)

In [ ]:
torch.randn((32))

In [ ]:
torch.randn((1,32))

In [ ]:
testrow[0].size()

In [ ]:
fakedata = torch.randn((4,3,300,200))

In [ ]:
torch.randn((50,33))

In [ ]:
fakemodel = covers.CoversGenreModel(33)

In [ ]:
fakedata

In [ ]:
fakeoutput = fakemodel(fakedata)

In [ ]:
fakeoutput.size()

In [ ]:
convlayer = torch.nn.Conv2d(3, 1, (3,3), padding=1)

In [ ]:
convoutput = convlayer(fakedata)

In [ ]:
convoutput.size()

In [ ]:
convoutput.squeeze(1).size()

In [ ]:
convsqueeze = convoutput.squeeze(1)

In [ ]:
convsqueeze.size()

In [ ]:
flattened = convsqueeze.view([4, 300*200])

In [ ]:
convoutput

In [ ]:
convoutput[2]

In [ ]:
convoutput[2].size()

In [ ]:
torch.Tensor([[2,3]]).size()

In [ ]:
flattened.size()

In [ ]:
model = covers.CoversGenreModel(33, 300, 200)

In [ ]:
model(testrow[0])

In [ ]:
testrow[0]

In [ ]:
testrow[0].size()

In [ ]:
testrow[0].unsqueeze(0).size()

In [ ]:
testoutput = model(testrow[0].unsqueeze(0))

In [ ]:
testrow[0].dtype

In [ ]:
convlayer(testrow[0]).size()

In [ ]:
testrow[1]

In [ ]:
loss = torch.nn.NLLLoss()

In [ ]:
myloss = loss(testoutput, torch.LongTensor([testrow[1]]))

In [ ]:
testrow[1]

In [ ]:
torch.Tensor([testrow[1]])

In [ ]:
myloss.backward()

In [ ]:
next(model.linear.parameters()).grad

In [ ]:
myloss

In [ ]:
next(model.linear.parameters())

In [ ]:
training_set, test_set = torch.utils.data.random_split(coversdataset, (0.7,0.3))

In [ ]:
training_set[5]

In [ ]:
import tqdm

In [ ]:
loader = torch.utils.data.DataLoader(coversdataset, batch_size=25, shuffle=True)

In [ ]:
loader_enum = enumerate(loader)

In [ ]:
next(loader_enum)

In [ ]:
loader_output = next(loader_enum)

In [ ]:
loader_output[1][1]

In [2]:
train_set, test_set, model = covers.create_env("../data/main_dataset.csv", "../data/", (300,200), actualsize=0.01)

In [ ]:
model

In [3]:
covers.train(train_set, model)

  0%|                                                     | 0/5 [00:00<?, ?it/s]/home/xsayas@GU.GU.SE/.local/lib/python3.11/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
100%|█████████████████████████████████████████████| 5/5 [00:11<00:00,  2.24s/it]


At epoch 0, we get loss 1688.2069473266602.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.09it/s]


At epoch 1, we get loss 1530.7977142333984.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.98it/s]


At epoch 2, we get loss 695.1732635498047.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.43it/s]


At epoch 3, we get loss 301.9839725494385.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.17it/s]


At epoch 4, we get loss 181.8507490158081.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.61it/s]


At epoch 5, we get loss 129.53413374419324.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  3.11it/s]


At epoch 6, we get loss 44.814183712005615.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.67it/s]


At epoch 7, we get loss 46.082524061203.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.13it/s]


At epoch 8, we get loss 7.312063694000244.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.75it/s]


At epoch 9, we get loss 6.980932980775833.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.87it/s]


At epoch 10, we get loss 3.4221680760383606.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  6.73it/s]


At epoch 11, we get loss 10.520961940288544.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.77it/s]


At epoch 12, we get loss 0.1906563473199956.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.98it/s]


At epoch 13, we get loss 19.134417815154166.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.64it/s]


At epoch 14, we get loss 11.210223108530045.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.79it/s]


At epoch 15, we get loss 4.566884607076645.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  6.23it/s]


At epoch 16, we get loss 4.475271135697053.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.16it/s]


At epoch 17, we get loss 1.6383904814720154.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.50it/s]


At epoch 18, we get loss 28.903905391693115.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.18it/s]


At epoch 19, we get loss 6.419250935316086.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.16it/s]


At epoch 20, we get loss 2.809007415996575.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.10it/s]


At epoch 21, we get loss 3.1716872453689575.


100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  5.63it/s]


At epoch 22, we get loss 2.9602328687906265.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.80it/s]


At epoch 23, we get loss 7.04601925611496.


100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  4.74it/s]

At epoch 24, we get loss 2.2715539932250977.


In [ ]:
import torch
a = torch.LongTensor(0)

In [ ]:
a

In [ ]:
a = torch.FloatTensor(6)

In [ ]:
a

In [ ]:
torch.argmax(-a) == 5

In [ ]:
a[0]

In [4]:
covers.test(test_set, model)

Accuracy = 0.041237113402061855
Confusion = [[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 0 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 

(0.041237113402061855,
 array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
      

In [ ]:
import torchmetrics

In [ ]:
import torcheval